modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/gidexplayyt-ops/custom-chat-mod/issues"

[[mods]]
modId="customchat"
version="1.0.0"
displayName="Custom Chat Mod"
displayURL="https://github.com/gidexplayyt-ops/custom-chat-mod"
authors="GidexPlayYT"
description='''
Кастомный чат по центру экрана с головами игроков и цветными никами.'''

[[dependencies.customchat]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.customchat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
